### ISSUE TITLE
Comment (visible to the recipient) - not in template, so not visible after all?

### ISSUE THREAD

**Issue by nblom** [halon/sender-fp-release#4]
It seems like the comment is not in templates/mail.twig, so the comment does not actually get sent to the recipient, even though the site states so.

<img width="775" alt="Skärmavbild 2020-04-30 kl  09 56 50" src="https://user-images.githubusercontent.com/8099285/80686409-f4994880-8ac8-11ea-954f-dd734ea927ce.png">

**Comment by fredriklengstrand** [comment]
Hello,

You should be able to see it when clicking on the link in the email:

https://github.com/halon/sender-fp-release/blob/master/templates/release.twig#L21

**Comment by nblom** [comment]
Thats true. So not a bug then =)
